[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

include = [
    "src/**/*",
]

# Cargo.toml
[dependencies]
dirs = "5.0.1"
image = "0.24.7"
minifb = "0.25.0"
nalgebra = "0.32.3"
wgpu = "0.17.1"
